#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/linuxserver/syncthing
  # -- image tag
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Specify the user ID the application will run as
  PUID: "568"
  # -- Specify the group ID the application will run as
  PGID: "568"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8384
  listen:
    enabled: true
    type: NodePort
    externalTrafficPolicy: Local
    ports:
      listen:
        enabled: true
        port: 22000
        protocol: TCP
        targetPort: 22000
  discovery:
    enabled: true
    type: NodePort
    externalTrafficPolicy: Local
    ports:
      discovery:
        enabled: true
        port: 21027
        protocol: UDP
        targetPort: 21027

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /var/syncthing
