remote: origin
target-branch: master
helm-extra-args: --timeout 600s
chart-dirs:
  - charts/incubator
  - charts/stable
excluded-charts:
chart-repos:
  - k8s-at-home-library=https://library-charts.k8s-at-home.com
  - k8s-home-lab=https://k8s-home-lab.github.io/helm-charts/
  - jetstack=https://charts.jetstack.io
