apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{ if .Values.postgresql.enabled }}
  POSTGRES_HOST: bitmagnet-postgres
  {{ end }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | toJson }}
  {{- end }}
