{{- include "common.values.setup" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  VPN_PROTOCOL: {{ "wireguard" | b64enc }}
  DISABLE_IPV6: {{ .Values.config.DISABLE_IPV6 | b64enc }}
  AUTOCONNECT: {{ .Values.config.AUTOCONNECT | b64enc }}
  PREFERRED_REGION: {{ .Values.config.PREFERRED_REGION | b64enc }}
  {{ if .Values.config.MAX_LATENCY }}
  MAX_LATENCY: {{ .Values.config.MAX_LATENCY | b64enc }}
  {{ end }}
  PIA_DNS: {{ .Values.config.PIA_DNS | b64enc }}
  PIA_PF: {{ .Values.config.PIA_PF | b64enc }}
  DIP_TOKEN: {{ .Values.config.DIP_TOKEN | b64enc }}
  PIA_USER: {{ .Values.config.PIA_USER | b64enc }}
  PIA_PASS: {{ .Values.config.PIA_PASS | b64enc }}
