apiVersion: v2
# renovate: image=ghcr.io/bitmagnet-io/bitmagnet
appVersion: v0.10
description: bitmagnet is a BitTorrent indexer, DHT crawler, content classifier and torrent search engine
name: bitmagnet
version: 1.1.0
kubeVersion: ">=1.32.0"
keywords:
  - bitmagnet
home: https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/bitmagnet
icon: https://raw.githubusercontent.com/bitmagnet-io/bitmagnet/main/bitmagnet.io/assets/images/favicon.png
sources:
  - https://github.com/bitmagnet-io/bitmagnet
  - https://github.com/k8s-home-lab/helm-charts/tree/master/charts/stable/bitmagnet
maintainers:
  - name: k8s-home-lab
    email: admin@aste.tools
dependencies:
  - name: common
    repository: https://k8s-home-lab.github.io/helm-charts/
    version: 4.5.5
  - name: postgres
    version: 0.19.6
    repository: oci://ghcr.io/cloudpirates-io/helm-charts
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Applied minor update of image postgres to 0.19.6
