apiVersion: v1
kind: Secret
metadata:
  name: {{ template "uptimerobot.fullname" . }}
  labels:
    app: {{ template "uptimerobot.name" . }}
    chart: {{ template "uptimerobot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  uptimerobot-apikey: {{ .Values.config.uptimerobot.apikey | b64enc | quote }}
  {{- if .Values.config.influxdb.username }}
  influxdb-username: {{ .Values.config.influxdb.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.influxdb.password }}
  influxdb-password: {{ .Values.config.influxdb.password | b64enc | quote }}
  {{- end }}
