#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: benbusby/whoogle-search
  # -- image tag
  tag: 0.5.4
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://github.com/benbusby/whoogle-search#environment-variables) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # WHOOGLE_CONFIG_COUNTRY:
  # WHOOGLE_CONFIG_DARK: 1
  # WHOOGLE_CONFIG_SAFE:
  # WHOOGLE_CONFIG_ALTS:
  # WHOOGLE_CONFIG_TOR:
  # WHOOGLE_CONFIG_NEW_TAB:
  # WHOOGLE_CONFIG_GET_ONLY:
  # WHOOGLE_CONFIG_URL: https://<your url>/
  # WHOOGLE_CONFIG_STYLE:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
