#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/aste88/brave/sync
  # -- image tag
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [gitea documentation](https://gitea.org/docs).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  AWS_ACCESS_KEY_ID: \#
  AWS_SECRET_ACCESS_KEY: \#
  AWS_REGION: eu-central-1
  TABLE_NAME: client-entity-dev
  AWS_ENDPOINT: http://brave-sync-dynamo-db:8000
  REDIS_URL: brave-sync-redis-headless:6379

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence: {}
  # data:
  #   enabled: false
  #   mountPath: /data

# -- Enable and configure redis subchart under this key.
#    For more options see [redis chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/redis)
# @default -- See values.yaml
redis:
  enabled: false
  architecture: standalone
  auth:
    enabled: true
    password: csjndlascxaj
  master:
    persistence:
      size: 6Gi

dynamo-db:
  enabled: false
  persistence:
  data:
    enabled: false
    mountPath: /data