---
apiVersion: v2
appVersion: 2.00.18
description: recyclarr is a self hosted web-app for automating media library transcode/remux management and making sure your files are exactly how you need them to be in terms of codecs/streams/containers etc.
name: recyclarr
version: 4.6.2
keywords:
  - transcoding
  - remux
  - media
  - video
home: https://github.com/Aste88/helm-charts/tree/master/charts/stable/recyclarr
icon: https://s7.gifyu.com/images/GifCroppedTran.gif
sources:
  - https://www.github.com/HaveAGitGat/recyclarr
  - https://hub.docker.com/r/haveagitgat/recyclarr/
  - https://recyclarr.io/docs/
maintainers:
  - name: auricom
    email: k8s-at-home@xpander.eml.cc
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
